# Generated by Django 2.2.19 on 2021-03-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobre_rece_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='zip_code',
            field=models.SlugField(max_length=6),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('charity', 'Charity'), ('ngo', 'Non-governmental organisation'), ('local', 'Local')], default='charity', max_length=7),
        ),
    ]
