# Generated by Django 2.2.19 on 2021-03-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobre_rece_app', '0002_auto_20210306_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
